name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  STACK_NAME: hyp3-nasa-disasters
  AWS_REGION: us-west-2
  TEMPLATE_FILE: cloudformation.yml

  AWS_ROLE_ARN: ${{ secrets.V2_AWS_ROLE_ARN }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.TOOLS_BOT_PAK }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file ${TEMPLATE_FILE} \
            --role-arn ${CLOUDFORMATION_ROLE_ARN} \
            --capabilities CAPABILITY_IAM
