name: Process and Transfer

on:
  schedule:
    # Run every six hours, on the hour
    - cron: '0 */6 * * *'
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}

jobs:
  process-and-transfer:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: Hurricanes
            config_file: data_management/hurricanes.json
          - environment: Floods
            config_file: data_management/floods.json
          - environment: Alaska
            config_file: data_management/alaska.json
          - environment: HKHwatermaps
            config_file: data_management/hkh_watermaps.json

    environment:
      name: ${{ matrix.environment }}

    env:
      EDL_USERNAME: ${{ secrets.EARTHDATA_LOGIN_USER }}
      EDL_PASSWORD: ${{ secrets.EARTHDATA_LOGIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: data_management/environment.yml
          extra-specs: |
            python=3.9

      - name: Process new granules
        continue-on-error: true
        shell: bash -l {0}
        run: |
          python data_management/process_new_granules.py -y -w ${{ matrix.config_file }}

      - name: Transfer new products
        shell: bash -l {0}
        run: |
          python data_management/hyp3_transfer_script.py -y ${{ matrix.config_file }}
