name: Static code analysis

on: push

jobs:

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: scottbrenner/cfn-lint-action@v2.3.2
        with:
          args: "--template cloudformation.yml"
