name: Static code analysis

on: push

jobs:

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: scottbrenner/cfn-lint-action@v2.4.2
        with:
          args: "--template cloudformation.yml"
