name: Static code analysis

on: push

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - run: |
          cfn-lint --info --template cloudformation.yml
